name: WPF apps build

on:
  push:
    branches: main

jobs:
    build:
        steps:
        - uses: nuget/setup-nuget@v1
          with:
            nuget-version: '6.x'
        #    nuget-api-key: ${{ secrets.NuGetAPIKey }}

        - name: Get Source Code
        - uses: actions/checkout@main
  
        - name: Restore nuget packages
        - run: nuget restore TestingGithubActions.sln

        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1

        - name: Build the solution
          run: msbuild TestingGithubActions.sln -t:rebuild -verbosity:diag -property:Configuration=Debug
        #  run: msbuild src\TestingGithubActions.sln -t:rebuild -verbosity:diag -property:Configuration=Debug

