name: WPF apps build

on:
  push:
    branches: main

jobs:
    build:

        runs-on: windows-latest

        steps:
        - name: Get Nuget Tool
          uses: nuget/setup-nuget@v1
          with:
            nuget-version: '6.x'
        #    nuget-api-key: ${{ secrets.NuGetAPIKey }}

        - name: Get Source Code
          uses: actions/checkout@v3
          with:
            ref: main
  
        - name: Restore nuget packages
          run: nuget restore TestingGithubActions\TestingGithubActions.sln

        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1

        - name: Build the solution
          run: msbuild TestingGithubActions\TestingGithubActions.sln -t:rebuild -verbosity:diag -property:Configuration=Debug
        #  run: msbuild src\TestingGithubActions.sln -t:rebuild -verbosity:diag -property:Configuration=Debug

        - name: Push Artifacts back to Github
          uses: actions/upload-artifact@v3
          with:
            name: TestingGithubActions App
            path: TestingGithubActions\bin\Debug\

